Supports image textures with transparency.
maxxfrazer/FocusEntity pull request #14
Opened 2021-01-26 21:31 UTC by Reality-Dev

Now you can upload your own image textures and use them for the diffuse of your focus entity, instead of just the segment edges or a plane mesh. 
      try .texture(.load(named: "Add"))
^^put your image in Assets.xcassets, and then place its (exact) name in that string above.
Transparency will be respected (e.g. if you upload a png texture that looks like a circle, the focus entity will look like a circle).
---
     static var defaultPlane: MeshResource {}
^^this plane was showing up far too large, so I commented it out.

2021-01-27 08:59 UTC, maxxfrazer requested changes
Thanks for this PR! Great to have this previously overlooked feature added; I like the use of MaterialColorParameter, really makes it simple to choose between a plain colour and a texture.
Feel free to add a section at the bottom of the Usage section of the README if you have chance, otherwise I can add it with the 1.3.0 release.

A few changes but they're all small ones!
I just realised the SwiftLint Github Action isn't working right on this repo, I'll fix that and adjust the other problems after this is merged.

2021-01-27 08:59 UTC, maxxfrazer commented on FocusEntity-Example/FocusEntity-Example/FocusARView.swift
> +    //self.focusEntity = FocusEntity(on: self, focus: .classic)
Let's leave the example project showing the classic version, with the texture version commented

2021-01-27 08:59 UTC, maxxfrazer commented on FocusEntity-Example/FocusEntity-Example/FocusARView.swift
> +        let offColor : MaterialColorParameter = try .texture(.load(named: "Open"))
bit nit-picky, but could you standardise the colons here removing that first space? (`onColor: Materi...`)

2021-01-27 08:59 UTC, maxxfrazer commented on Sources/FocusEntity/FocusEntity+Colored.swift
> +
Please delete these trailing spaces

2021-01-27 08:59 UTC, maxxfrazer commented on Sources/FocusEntity/FocusEntity+Colored.swift
> +    modelMaterial.tintColor = UIColor.white.withAlphaComponent(0.99)
Use `Material.Color.white...` instead, then remove UIKit import

2021-01-27 08:59 UTC, maxxfrazer commented on Sources/FocusEntity/FocusEntityComponent.swift
> +        nonTrackingColor: MaterialColorParameter.color(UIColor.red.withAlphaComponent(0.2)),
Same here for removing UIKit & `Material.Color.red.with...`

2021-01-27 08:59 UTC, maxxfrazer commented on Sources/FocusEntity/FocusEntityComponent.swift
> +        mesh: MeshResource.generatePlane(width: 0.1, depth: 0.1)
Could you fix the spacing here? (mix of 2 and 4 spaces, rest of the repo uses 2 spaces)

2021-01-27 08:59 UTC, maxxfrazer commented on Sources/FocusEntity/FocusEntityComponent.swift
> +
Go ahead and delete this, I think it was used in a previous version, d'oh

2021-01-28 11:43 UTC, maxxfrazer approved these changes

2021-01-28 11:45 UTC, merged

2021-01-29 00:42 UTC, Reality-Dev commented
I just saw these extra comments. Thanks for getting it fixed up and ready to go so quickly! I have more updates on the way coming soon (which will probably require substantially more revisions). Great work!